### PR TITLE
fix: pet-generation-form style changed

### PR DESCRIPTION
**Pull request by AdityaSinha2305**

### CODE REVIEW

**Comment by AdityaSinha2305** [comment]
Please check this update and do merge it upon successful review!
Assign this under hacktoberfest.

**Comment by cocomantis** [comment]
Thank you for the contribution!

**Comment by AdityaSinha2305** [comment]
Can you specifically add "hacktoberfest" label to this pr apart from other labels?

**Comment by AdityaSinha2305** [comment]
@cocomantis Can you add this under 'gssoc-ext' label as well ?

**Pull request merged**
