### PR TITLE
Add Dark Mode/ Light Mode Successfully 

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
Hi @cocomantis, I have successfully added the dark/light mode toggle. You can check it out 👍  

Enhancing user engagement with a dark mode toggle and enabling users to log in will improve the interactivity of the website. The dark mode provides a better visual experience, while user authentication will allow personalized content.

I haven’t integrated the login system or User Authentication Functionality yet but I will create a new issue later with 2-3 professional features for user authentication. For now feel free to merge this and take a look.

Mode

### CODE REVIEW

**Comment by cocomantis** [comment]
Thank you please, resolve the conflicts before I can merge the pull request!

**Comment by syedmaazsaeed** [comment]
Welcome. My Pleasure. Yes Sure Resolved Successfully.

**Comment by cocomantis** [comment]
I am unable to merge it due to conflicts, it seems the conflicts are still there.

**Comment by syedmaazsaeed** [comment]
okay.

**Comment by syedmaazsaeed** [comment]
@cocomantis  Yes Sure Resolved conflicts successfully.

**Comment by cocomantis** [comment]
Thank you for your contribution!

**Comment by syedmaazsaeed** [comment]
Welcome.My Pleasure

**Pull request merged**
