### PR TITLE
Feat: Real pet-name added and updated form

### LINKED ISSUE #25: Pet-form styling changed
I have changed the pet-form styling.
Assign me this under hacktoberfest.

image

### PR DESCRIPTION
**Pull request by AdityaSinha2305**
Issue resolved  #25  #39 #40 

I have added real pet name along with that I have updated the form input which ask information more related to pet oriented.
If everything looks fine do merge this under 'hacktoberfest' and 'hacktoberfest-accepted' label.

This is how it looks.

image

Pet Types :
image

Pet Traits :
image

Pet Colours : 
image
 

Name Generated :
image

### CODE REVIEW

**Comment by Taj-2005** [comment]
please assign this task to me for Hacktoberfest2024

**Comment by AdityaSinha2305** [comment]
@cocomantis Can you add this under 'hacktoberfest' and 'gssoc-ext' label as well ?

**Comment by cocomantis** [comment]
Hello thank you for the contribution, I am unable to merge the request due to the conflicts in the main branch. Please resolve them.

**Comment by AdityaSinha2305** [comment]
@cocomantis I have resolved the conflicts you can check now.

**Pull request merged**
